baseURL = "https://bhrigu.me"
title = "Bhrigu Srivastava"
copyright = "Copyright © 2016–2020, Bhrigu Srivastava; all rights reserved."
paginate = 2
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
googleAnalytics = "UA-64358360-1"
DisqusShortname = "bhrigu"
theme = "hugo-theme-chunky-poster-fork"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 10
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 0

[taxonomies]
category = "categories"
tag = "tags"
series = "series"
author = "authors"

[params]
  author = "Bhrigu Srivastava"
  description = "Developer | Software Engineer "
  homepageImage = "/images/homepage-image.jpg"
  dateFormat = "January 2, 2006"
  share = true
  showLanguageSwitcher = false

  # Custom CSS and JS. Relative to /static/css and /static/js respectively.
  customCSS = []
  customJS = []

  [params.social]
    rss = true
    email = "captain.bhrigu@gmail.com"
    facebook = "https://www.facebook.com/bhrigu123/"
    twitter = "https://twitter.com/CaptainBhrigu"
    github = "https://github.com/bhrigu123/"

  [params.prismJS]
    enable = true
    theme = "okaidia"

[markup]
  [markup.highlight]
    codeFences = false

[services]
  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true